<?php
/**
 * HTTP API for operational step recipe editor (session workflow / simulator).
 *
 * AGENT BREADCRUMB — when changing actions or request/response shapes, also update:
 *   sts/operational_steps_api.openapi.yaml
 *   sts/operational_steps_api-docs.html (banner links only)
 *   sts-docker/AGENTS.md § Operational Steps API
 * Command/step param schemas: GET ?action=catalog; Swagger docs generated by
 *   sts/generate_operational_steps_openapi_catalog.php → operational_steps_catalog.openapi.generated.yaml
 *
 * GET  ?action=catalog|list_workflows|recipe|run_options|compile|download
 * POST ?action=save|run_switchlists|import_workflow|normalize_recipe|set_active_workflow|delete_workflow|compile
 *      (action in query, form field, or JSON body)
 */

header('Content-Type: application/json; charset=utf-8');

$sts_dir = __DIR__;
require_once $sts_dir . '/open_db.php';
require_once $sts_dir . '/operational_steps_catalog.php';
require_once $sts_dir . '/session_helpers.php';

$session_dir = operational_steps_editor_dir();
$body = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $body = operational_steps_api_body();
}
$action = $_GET['action'] ?? $_POST['action'] ?? ($body['action'] ?? '');

function operational_steps_api_json($data, $code = 200)
{
    http_response_code($code);
    echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    exit;
}

function operational_steps_api_body()
{
    static $cached = null;
    if ($cached !== null) {
        return $cached;
    }
    $raw = file_get_contents('php://input');
    $data = json_decode($raw, true);
    $cached = is_array($data) ? $data : [];
    return $cached;
}

function operational_steps_api_workflow_file(array $sources, $session_dir)
{
    $requested = $sources['workflow_file'] ?? $sources['csv_file'] ?? null;
    return operational_steps_active_workflow($session_dir, $requested);
}

try {
    switch ($action) {
        case 'catalog':
            $dbc = open_db();
            $dynamic = operational_steps_fetch_dynamic_options($dbc);
            mysqli_close($dbc);
            operational_steps_api_json([
                'ok' => true,
                'categories' => operational_steps_catalog_categories(),
                'adder_categories' => operational_steps_catalog_adder_categories(),
                'dynamic_options' => $dynamic,
                'functions' => operational_steps_catalog_definitions(),
                'adder_functions' => operational_steps_catalog_adder_definitions(),
            ]);

        case 'run_options':
            $workflow_file = operational_steps_api_workflow_file($_GET, $session_dir);
            $recipe = operational_steps_load_recipe($session_dir, $workflow_file);
            $compiled = operational_steps_compile_recipe($recipe);
            $indices = operational_steps_recipe_indices($recipe);
            $dbc = open_db();
            $current_session = session_get_db_session($dbc);
            $condition_context = session_evaluate_context($dbc, []);
            unset(
                $condition_context['_dbc'],
                $condition_context['_config'],
                $condition_context['_runtime_limited']
            );
            mysqli_close($dbc);
            $existing = operational_steps_discover_switchlist_sessions($session_dir);
            operational_steps_api_json([
                'ok' => true,
                'current_session' => $current_session,
                'existing_sessions' => $existing,
                'indices' => $indices,
                'default_breakpoint' => $indices['total'] ?: count($recipe['steps'] ?? []),
                'default_start' => 1,
                'default_stop' => $indices['total'] ?: count($recipe['steps'] ?? []),
                'breakpoints' => $indices['breakpoints'],
                'compiled' => $compiled,
                'condition_context' => $condition_context,
            ]);

        case 'list_workflows':
        case 'list_csv':
            $files = operational_steps_list_workflow_files($session_dir);
            $active = operational_steps_resolve_active_workflow($session_dir, $_GET['workflow_file'] ?? $_GET['csv_file'] ?? null);
            operational_steps_api_json([
                'ok' => true,
                'files' => $files,
                'active_workflow' => $active,
                'auto_load' => count($files) === 1,
            ]);

        case 'recipe':
            $workflow_file = operational_steps_api_workflow_file($_GET, $session_dir);
            $recipe = operational_steps_load_recipe($session_dir, $workflow_file);
            operational_steps_api_json([
                'ok' => true,
                'recipe' => $recipe,
                'workflow_file' => $workflow_file ?: ($recipe['source_workflow'] ?? ''),
                'compiled' => operational_steps_compile_recipe($recipe),
            ]);

        case 'compile':
            $body = operational_steps_api_body();
            $recipe = $body['recipe'] ?? operational_steps_load_recipe($session_dir);
            operational_steps_api_json([
                'ok' => true,
                'compiled' => operational_steps_compile_recipe($recipe),
            ]);

        case 'save':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            if (empty($body['recipe']) || !is_array($body['recipe'])) {
                operational_steps_api_json(['ok' => false, 'error' => 'Missing recipe'], 400);
            }
            $recipe = $body['recipe'];
            if (!isset($recipe['version'])) {
                $recipe['version'] = 1;
            }
            $workflow_file = operational_steps_api_workflow_file($body, $session_dir);
            $save = operational_steps_save_recipe($session_dir, $recipe, $workflow_file);
            if (empty($save['written'])) {
                operational_steps_api_json(['ok' => false, 'error' => implode('; ', $save['errors'])], 500);
            }
            operational_steps_api_json([
                'ok' => true,
                'written' => $save['written'],
                'warnings' => $save['errors'],
                'compiled' => $save['compiled'],
                'rows' => count($save['compiled']),
                'workflow_file' => $save['workflow_file'] ?? $workflow_file,
            ]);

        case 'run_switchlists':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            $format = $body['format'] ?? 'all';
            $jobs = isset($body['jobs']) ? array_values(array_filter(array_map('trim', explode(',', $body['jobs'])))) : [];
            if (isset($body['recipe']) && is_array($body['recipe'])) {
                operational_steps_save_recipe(
                    $session_dir,
                    $body['recipe'],
                    operational_steps_api_workflow_file($body, $session_dir)
                );
            }
            $recipe = isset($body['recipe']) && is_array($body['recipe'])
                ? $body['recipe']
                : operational_steps_load_recipe($session_dir);
            $recipe = operational_steps_normalize_recipe($recipe);
            $mode = $body['mode'] ?? 'current';
            $render_sessions = [];
            if (!empty($body['render_sessions']) && is_array($body['render_sessions'])) {
                $render_sessions = array_map('intval', $body['render_sessions']);
            } elseif (!empty($body['sessions']) && is_array($body['sessions'])) {
                $render_sessions = array_map('intval', $body['sessions']);
                if ($mode === 'current') {
                    $mode = 'rerender';
                }
            }
            $dbc = open_db();
            $result = operational_steps_run_generator_web($dbc, [
                'recipe' => $recipe,
                'format' => $format,
                'jobs' => $jobs,
                'mode' => $mode,
                'start_step' => (int) ($body['start_step'] ?? 0),
                'stop_step' => (int) ($body['stop_step'] ?? 0),
                'breakpoint_step' => (int) ($body['breakpoint_step'] ?? 0),
                'session_count' => (int) ($body['session_count'] ?? 1),
                'run_prep' => !isset($body['run_prep']) || (bool) $body['run_prep'],
                'play_after' => !isset($body['play_after']) || (bool) $body['play_after'],
                'render_sessions' => $render_sessions,
            ]);
            mysqli_close($dbc);
            $lines = [];
            foreach ($result['cycles'] as $cycle) {
                $lines[] = sprintf(
                    'Session %s — %d phase(s)%s',
                    $cycle['session'],
                    (int) ($cycle['phases'] ?? 0),
                    !empty($cycle['stopped']) ? ' (stopped)' : ''
                );
                foreach ($cycle['written'] ?? [] as $item) {
                    if (!is_array($item)) {
                        continue;
                    }
                    $lines[] = sprintf(
                        '  %s: %d phase(s), %d car(s)',
                        $item['job'] ?? '?',
                        $item['phases'] ?? 0,
                        $item['cars'] ?? 0
                    );
                }
            }
            $last = end($result['cycles']);
            operational_steps_api_json([
                'ok' => true,
                'mode' => $result['mode'],
                'breakpoint_step' => $result['breakpoint_step'],
                'start_step' => $result['start_step'] ?? null,
                'stop_step' => $result['stop_step'] ?? null,
                'sessions' => $result['sessions'],
                'session' => $last ? $last['session'] : '',
                'format' => $format,
                'jobs' => $jobs,
                'summary' => $lines,
                'warnings' => $result['warnings'] ?? [],
                'cycles' => $result['cycles'],
                'index_url' => '/sts/session_overview.php',
                'session_url' => $last ? '/sts/' . session_output_url('session_' . $last['session'] . '/index.php') : '/sts/session_overview.php',
            ]);

        case 'rerender_session_style':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            $session = (int) ($body['session'] ?? 0);
            $style = session_normalize_switchlist_style($body['style'] ?? 'mobile');
            if ($session < 1) {
                operational_steps_api_json(['ok' => false, 'error' => 'session required'], 400);
            }
            require_once __DIR__ . '/session_helpers.php';
            $force = !empty($body['force']);
            $dbc = open_db();
            $root = session_web_root();
            $manifest = session_load_manifest($session, $root);
            $already = session_session_style_available($session, $style, $manifest, $root);
            $results = session_rerender_session_style($dbc, $session, $style, $root, $force);
            mysqli_close($dbc);
            $skipped = count($results) > 0 && count(array_filter($results, static function ($r) {
                return !empty($r['skipped']);
            })) === count($results);
            operational_steps_api_json([
                'ok' => true,
                'session' => $session,
                'style' => $style,
                'skipped' => $already || $skipped,
                'results' => $results,
            ]);

        case 'build_print_all_style':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            require_once __DIR__ . '/session_helpers.php';
            $body = operational_steps_api_body();
            $session = (int) ($body['session'] ?? 0);
            $style = session_normalize_switchlist_style($body['style'] ?? 'mobile');
            if ($session < 1) {
                operational_steps_api_json(['ok' => false, 'error' => 'session required'], 400);
            }
            $dbc = open_db();
            $root = session_web_root();
            $rel = session_build_switchlist_print_all_style($dbc, $session, $style, $root);
            mysqli_close($dbc);
            if ($rel === null) {
                operational_steps_api_json(['ok' => false, 'error' => 'No switch lists to render for this style'], 404);
            }
            operational_steps_api_json([
                'ok' => true,
                'session' => $session,
                'style' => $style,
                'url' => session_output_url($rel),
            ]);

        case 'normalize_recipe':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            if (!empty($body['use_file'])) {
                $workflow_file = operational_steps_api_workflow_file($body, $session_dir);
                if ($workflow_file === '') {
                    operational_steps_api_json(['ok' => false, 'error' => 'No workflow file selected'], 400);
                }
                $recipe = operational_steps_load_recipe($session_dir, $workflow_file);
            } else {
                $recipe = $body['recipe'] ?? operational_steps_load_recipe($session_dir);
                $recipe = operational_steps_normalize_recipe($recipe);
            }
            operational_steps_api_json([
                'ok' => true,
                'recipe' => $recipe,
                'compiled' => operational_steps_compile_recipe($recipe),
                'rows' => count($recipe['steps'] ?? []),
            ]);

        case 'import_workflow':
        case 'import_csv':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            if (!empty($body['recipe']) && is_array($body['recipe'])) {
                $recipe = operational_steps_normalize_recipe($body['recipe']);
            } elseif (!empty($body['use_file'])) {
                $workflow_file = operational_steps_api_workflow_file($body, $session_dir);
                if ($workflow_file === '') {
                    operational_steps_api_json(['ok' => false, 'error' => 'Choose a workflow file to load'], 400);
                }
                $recipe = operational_steps_load_recipe($session_dir, $workflow_file);
            } else {
                $raw = $body['workflow'] ?? $body['json'] ?? '';
                if ($raw === '') {
                    operational_steps_api_json(['ok' => false, 'error' => 'No workflow JSON content'], 400);
                }
                $data = is_array($raw) ? $raw : operational_steps_decode_recipe_json($raw);
                if (!is_array($data)) {
                    operational_steps_api_json(['ok' => false, 'error' => 'Invalid workflow JSON'], 400);
                }
                foreach ($data['steps'] ?? [] as $i => $step) {
                    if (is_array($step)) {
                        $data['steps'][$i]['structured_import'] = true;
                    }
                }
                $recipe = operational_steps_normalize_recipe($data);
            }
            if (!empty($body['workflow_file']) || !empty($body['csv_file'])) {
                operational_steps_set_active_workflow(
                    $session_dir,
                    operational_steps_api_workflow_file($body, $session_dir)
                );
            }
            operational_steps_api_json([
                'ok' => true,
                'recipe' => $recipe,
                'workflow_file' => operational_steps_active_workflow($session_dir),
                'compiled' => operational_steps_compile_recipe($recipe),
            ]);

        case 'set_active_workflow':
        case 'set_active_csv':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            $workflow_file = $body['workflow_file'] ?? $body['csv_file'] ?? '';
            if ($workflow_file === '') {
                operational_steps_api_json(['ok' => false, 'error' => 'Missing workflow_file'], 400);
            }
            $workflow_file = operational_steps_set_active_workflow($session_dir, $workflow_file);
            operational_steps_api_json(['ok' => true, 'active_workflow' => $workflow_file]);

        case 'delete_workflow':
            if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
                operational_steps_api_json(['ok' => false, 'error' => 'POST required'], 405);
            }
            $body = operational_steps_api_body();
            $workflow_file = trim((string) ($body['workflow_file'] ?? ''));
            if ($workflow_file === '') {
                operational_steps_api_json(['ok' => false, 'error' => 'Missing workflow_file'], 400);
            }
            $result = operational_steps_delete_workflow($session_dir, $workflow_file);
            operational_steps_api_json(array_merge(['ok' => true], $result));

        case 'download':
            $workflow_file = operational_steps_api_workflow_file($_GET, $session_dir);
            if ($workflow_file === '') {
                operational_steps_api_json(['ok' => false, 'error' => 'Choose a workflow file'], 400);
            }
            $paths = operational_steps_recipe_paths_for_workflow($session_dir, $workflow_file);
            $path = $paths['workflow'];
            if (!is_file($path)) {
                operational_steps_api_json(['ok' => false, 'error' => 'File not found'], 404);
            }
            header('Content-Type: application/json; charset=utf-8');
            header('Content-Disposition: attachment; filename="' . basename($path) . '"');
            header('Content-Length: ' . filesize($path));
            readfile($path);
            exit;

        default:
            operational_steps_api_json([
                'ok' => false,
                'error' => 'Unknown action',
                'actions' => [
                    'catalog', 'list_workflows', 'recipe', 'compile', 'save', 'run_switchlists', 'rerender_session_style',
                    'build_print_all_style',
                    'run_options', 'import_workflow', 'normalize_recipe', 'set_active_workflow', 'delete_workflow', 'download',
                ],
            ], 400);
    }
} catch (Throwable $e) {
    operational_steps_api_json(['ok' => false, 'error' => $e->getMessage()], 500);
}
