-- HART layout seed data for STS
-- Generated by scripts/generate_hart_seed.py — do not edit by hand

SET NAMES utf8mb4;

-- pu_criteria is created by open_db.php on first web visit; ensure it exists for seed/reseed
CREATE TABLE IF NOT EXISTS `pu_criteria` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` varchar(64) DEFAULT NULL,
  `step_nbr` int(11) DEFAULT NULL,
  `car_status` varchar(256) DEFAULT NULL,
  `commodity_id` int(11) DEFAULT NULL,
  `car_code_id` int(11) DEFAULT NULL,
  `dest_station_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `pu_criteria` MODIFY `job_id` varchar(64) DEFAULT NULL;

UPDATE `settings` SET `setting_value` = 'HART Railroad, Pittsburgh & Chartiers Valley Division' WHERE `setting_name` = 'railroad_name';
UPDATE `settings` SET `setting_value` = 'HART' WHERE `setting_name` = 'railroad_initials';

INSERT INTO `routing` (`id`, `station`, `station_nbr`, `instructions`, `sort_seq`, `color1`, `color2`) VALUES
(11, 'North Yard', 1, 'SY1 yardmaster staging.\nCars for island industries or South Yard classification.', 150, 0, 0),
(2, 'West Yard', 2, 'SY1 yardmaster retrieves and stages cars.', 200, 0, 0),
(9, 'Scully Yard', 5, 'POHC interchange — NVL set out outbound; pick up inbound.', 250, 0, 0),
(12, 'East Yard', 3, 'Coke storage — CK-1 to South Yard when authorized.\nSY1 yardmaster staging.', 275, 0, 0),
(3, 'Neville Island', NULL, 'Island locals — NVL spots and pulls at Aristech, Stucki, Calgon, Ferrel, and Kosmos.', 300, 0, 0),
(8, 'South Yard', 4, 'Classification hub for D749 and NVL.\nInbound CSX for D749 (Demmler); POHC for NVL (Scully).\nIndustry-bound locals for NVL.', 800, 0, 0),
(10, 'Demmler Yard', 6, 'CSX interchange — D749 set out outbound; pick up inbound.', 850, 0, 0);

INSERT INTO `locations` (`Id`, `code`, `station`, `track`, `spot`, `rpt_station`, `remarks`, `color`) VALUES
(1, 'NORTH-YARD', 11, 'Yard', '', '', '', ''),
(2, 'WEST-YARD', 2, 'Yard', '', '', '', ''),
(3, 'EAST-YARD', 12, 'Yard', '', '', '', ''),
(4, 'SOUTH-YARD', 8, 'Yard', '', '', '', ''),
(5, 'SCULLY', 9, 'Yard', '', '', 'POHC', ''),
(6, 'DEMMLER', 10, 'Yard', '', '', 'CSX', ''),
(7, 'NIL-CALG-Coal', 3, 'Calgon Carbon', 'Coal Unload', '', '', ''),
(8, 'NIL-CALG-Carbon', 3, 'Calgon Carbon', 'Carbon Load', '', '', ''),
(9, 'NIL-CALG-Chemical', 3, 'Calgon Carbon', 'Chemical Unload', '', '', ''),
(10, 'NIL-KOSM-Cement', 3, 'Kosmos Cement', 'Cement Unload', '', '', ''),
(11, 'NIL-KOSM-Aggregate', 3, 'Kosmos Cement', 'Aggregate Unload', '', '', ''),
(12, 'NIL-FERR-LPG', 3, 'Ferrel Gas', 'LPG Unload', '', '', ''),
(13, 'NIL-STUK-Crane', 3, 'A Stucki Co', 'Crane Track', '', '', ''),
(14, 'NIL-STUK-Team', 3, 'A Stucki Co', 'Team Track', '', '', ''),
(15, 'NIL-ARIS-Pellets', 3, 'Aristech Plastics', 'Pellet Unload', '', '', ''),
(16, 'NIL-ARIS-Chemical', 3, 'Aristech Plastics', 'Chemical Unload', '', '', ''),
(17, 'NIL-ARIS-Shipping', 3, 'Aristech Plastics', 'Shipping Door', '', '', '');

INSERT INTO `commodities` (`Id`, `Code`, `Description`, `Remarks`) VALUES
(1, 'ACTIVATEDCARBON', 'Activated Carbon', ''),
(2, 'AGGREGATE', 'Aggregate', ''),
(3, 'ARGON', 'Process Chemicals', ''),
(4, 'CAUSTICSODA', 'Process Chemicals', ''),
(5, 'CEMENT', 'Cement', ''),
(6, 'COAL', 'Coal', ''),
(7, 'ETHYLACRYLATE', 'Process Chemicals', ''),
(8, 'FLUORESCENTLAMPS', 'Fluorescent Lamps', ''),
(9, 'FLUORESCENTTUBES', 'Fluorescent Tubes', ''),
(10, 'FORGEDCOMPONENTS', 'Forged Components', ''),
(11, 'FROZENFOODS', 'Frozen Foods', ''),
(12, 'GENFREIGHT', 'General Freight', ''),
(13, 'HYDROCHLORICACID', 'Process Chemicals', ''),
(14, 'INDUSTRIALGASES', 'Process Chemicals', ''),
(15, 'LPG', 'LPG', ''),
(16, 'MACHINEDPARTS', 'General Freight', ''),
(17, 'METHYLMETHACRYLATE', 'Process Chemicals', ''),
(18, 'PACKAGEDMEATS', 'Packaged Meats', ''),
(19, 'PHOSPHORCOMPOUNDS', 'Process Chemicals', ''),
(20, 'PHOSPHORICACID', 'Process Chemicals', ''),
(21, 'PLASTICPELLETS', 'Plastic Pellets', ''),
(22, 'PLASTICRESINS', 'Plastic Resins', ''),
(23, 'PROCCHEM', 'Process Chemicals', ''),
(24, 'RAILWAYSPRINGS', 'General Freight', ''),
(25, 'SCRAPSTEEL', 'Scrap Steel', ''),
(26, 'STAINLESSBAR', 'Stainless Bar', ''),
(27, 'STAINLESSSLAB', 'Stainless Slab', ''),
(28, 'STEEL', 'Steel', ''),
(29, 'STEELBILLETS', 'Steel Billets', ''),
(30, 'STEELCOILS', 'General Freight', ''),
(31, 'STEELPLATE', 'Steel Plate', ''),
(32, 'STYRENEMONOMER', 'Process Chemicals', ''),
(33, 'TINPLATE', 'General Freight', '');

INSERT INTO `car_codes` (`Id`, `code`, `description`, `remarks`) VALUES
(1, 'FC', 'flatcar, center beam', ''),
(2, 'FM', 'flatcar, general service', ''),
(6, 'GA', 'gondola, open top', ''),
(3, 'HA', 'hopper, open top, gravity discharge inside rails', ''),
(4, 'HB', 'hopper, open top, gravity discharge outside rails', ''),
(7, 'HC', 'hopper, covered, gravity discharge', ''),
(8, 'HP', 'hopper, covered, pneumatic discharge', ''),
(10, 'RM', 'refrigerator, mechanical', ''),
(9, 'TA', 'tankcar, general service', ''),
(12, 'WC', 'work crane car, MOW service', ''),
(11, 'WF', 'work flatcar, MOW service', ''),
(5, 'XM', 'boxcar, general service', '');

INSERT INTO `shipments` (`Id`, `code`, `description`, `consignment`, `car_code`, `loading_location`, `unloading_location`, `last_ship_date`, `min_interval`, `max_interval`, `min_amount`, `max_amount`, `special_instructions`, `remarks`) VALUES
(1, 'ARIS-LOA-IN-001', 'Aristech Plastics — Plastic Pellets', 21, 8, 6, 15, 0, 0, 1, 0, 1, 'CSX', ''),
(2, 'ARIS-LOA-IN-002', 'Aristech Plastics — Plastic Pellets', 21, 8, 6, 15, 0, 0, 1, 0, 1, 'CSX', ''),
(3, 'ARIS-LOA-IN-003', 'Aristech Plastics — Plastic Pellets', 21, 8, 5, 15, 0, 0, 1, 0, 1, 'POHC', ''),
(4, 'ARIS-LOA-IN-004', 'Aristech Plastics — Ethyl Acrylate', 7, 9, 6, 16, 0, 0, 1, 0, 1, 'CSX', ''),
(5, 'ARIS-LOA-IN-005', 'Aristech Plastics — Methyl Methacrylate', 17, 9, 5, 16, 0, 0, 1, 0, 1, 'POHC', ''),
(6, 'ARIS-LOA-IN-006', 'Aristech Plastics — Styrene Monomer', 32, 9, 6, 16, 0, 0, 1, 0, 1, 'CSX', ''),
(7, 'ARIS-LOA-OUT-007', 'Aristech Plastics — Plastic Resins', 22, 5, 17, 5, 0, 0, 1, 0, 1, 'POHC', ''),
(8, 'ARIS-LOA-OUT-008', 'Aristech Plastics — Plastic Resins', 22, 5, 17, 5, 0, 0, 1, 0, 1, 'POHC', ''),
(9, 'ARIS-LOA-OUT-009', 'Aristech Plastics — Plastic Resins', 22, 5, 17, 6, 0, 0, 1, 0, 1, 'CSX', ''),
(10, 'STUK-LOA-IN-013', 'A Stucki Co — Steel', 28, 5, 6, 13, 0, 0, 1, 0, 1, 'CSX', ''),
(11, 'STUK-LOA-IN-014', 'A Stucki Co — Steel', 28, 2, 5, 13, 0, 0, 1, 0, 1, 'POHC', ''),
(12, 'STUK-LOA-IN-015', 'A Stucki Co — Steel', 28, 6, 5, 13, 0, 0, 1, 0, 1, 'POHC', ''),
(13, 'STUK-LOA-IN-016', 'A Stucki Co — Steel Coils', 30, 5, 6, 14, 0, 0, 1, 0, 1, 'CSX', ''),
(14, 'STUK-LOA-IN-017', 'A Stucki Co — Steel Plate', 31, 2, 6, 14, 0, 0, 1, 0, 1, 'CSX', ''),
(15, 'STUK-LOA-IN-018', 'A Stucki Co — Steel Billets', 29, 6, 5, 14, 0, 0, 1, 0, 1, 'POHC', ''),
(16, 'STUK-LOA-OUT-019', 'A Stucki Co — Machined Parts', 16, 5, 14, 6, 0, 0, 1, 0, 1, 'CSX', ''),
(17, 'STUK-LOA-OUT-020', 'A Stucki Co — Railway Springs', 24, 2, 14, 5, 0, 0, 1, 0, 1, 'POHC', ''),
(18, 'STUK-LOA-OUT-021', 'A Stucki Co — Steel Coils', 30, 6, 14, 6, 0, 0, 1, 0, 1, 'CSX', ''),
(19, 'CALG-LOA-IN-022', 'Calgon Carbon — Coal', 6, 3, 6, 7, 0, 0, 1, 0, 1, 'CSX', ''),
(20, 'CALG-LOA-IN-023', 'Calgon Carbon — Coal', 6, 3, 6, 7, 0, 0, 1, 0, 1, 'CSX', ''),
(21, 'CALG-LOA-IN-024', 'Calgon Carbon — Coal', 6, 3, 5, 7, 0, 0, 1, 0, 1, 'POHC', ''),
(22, 'CALG-LOA-OUT-025', 'Calgon Carbon — Activated Carbon', 1, 7, 8, 5, 0, 0, 1, 0, 1, 'POHC', ''),
(23, 'CALG-LOA-OUT-026', 'Calgon Carbon — Activated Carbon', 1, 7, 8, 6, 0, 0, 1, 0, 1, 'CSX', ''),
(24, 'CALG-LOA-OUT-027', 'Calgon Carbon — Activated Carbon', 1, 7, 8, 6, 0, 0, 1, 0, 1, 'CSX', ''),
(25, 'CALG-LOA-IN-028', 'Calgon Carbon — Caustic Soda', 4, 9, 5, 9, 0, 0, 1, 0, 1, 'POHC', ''),
(26, 'CALG-LOA-IN-029', 'Calgon Carbon — Hydrochloric Acid', 13, 9, 5, 9, 0, 0, 1, 0, 1, 'POHC', ''),
(27, 'CALG-LOA-IN-030', 'Calgon Carbon — Phosphoric Acid', 20, 9, 6, 9, 0, 0, 1, 0, 1, 'CSX', ''),
(28, 'FERR-LOA-IN-034', 'Ferrel Gas — LPG', 15, 9, 5, 12, 0, 0, 1, 0, 1, 'POHC', ''),
(29, 'FERR-LOA-IN-035', 'Ferrel Gas — LPG', 15, 9, 6, 12, 0, 0, 1, 0, 1, 'CSX', ''),
(30, 'FERR-LOA-IN-036', 'Ferrel Gas — LPG', 15, 9, 6, 12, 0, 0, 1, 0, 1, 'CSX', ''),
(31, 'KOSM-LOA-IN-037', 'Kosmos Cement — Cement', 5, 7, 5, 10, 0, 0, 1, 0, 1, 'POHC', ''),
(32, 'KOSM-LOA-IN-038', 'Kosmos Cement — Cement', 5, 7, 6, 10, 0, 0, 1, 0, 1, 'CSX', ''),
(33, 'KOSM-LOA-IN-039', 'Kosmos Cement — Cement', 5, 7, 5, 10, 0, 0, 1, 0, 1, 'POHC', ''),
(34, 'KOSM-LOA-IN-040', 'Kosmos Cement — Aggregate', 2, 6, 5, 11, 0, 0, 1, 0, 1, 'POHC', ''),
(35, 'KOSM-LOA-IN-041', 'Kosmos Cement — Aggregate', 2, 6, 6, 11, 0, 0, 1, 0, 1, 'CSX', ''),
(36, 'KOSM-LOA-IN-042', 'Kosmos Cement — Aggregate', 2, 3, 6, 11, 0, 0, 1, 0, 1, 'CSX', ''),
(37, 'IX-INT-XX-043', 'Fluorescent Lamps (POHC→CSX)', 8, 5, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(38, 'IX-INT-XX-044', 'Fluorescent Tubes (POHC→CSX)', 9, 5, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(39, 'IX-INT-XX-045', 'Plastic Resins (CSX→POHC)', 22, 5, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(40, 'IX-INT-XX-046', 'Steel Coils (POHC→CSX)', 30, 1, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(41, 'IX-INT-XX-047', 'Steel Coils (CSX→POHC)', 30, 1, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(42, 'IX-INT-XX-048', 'Tin Plate (POHC→CSX)', 33, 1, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(43, 'IX-INT-XX-049', 'Activated Carbon (CSX→POHC)', 1, 7, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(44, 'IX-INT-XX-050', 'Cement (POHC→CSX)', 5, 7, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(45, 'IX-INT-XX-051', 'Cement (POHC→CSX)', 5, 7, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(46, 'IX-INT-XX-052', 'Phosphor Compounds (CSX→POHC)', 19, 7, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(47, 'IX-INT-XX-053', 'Phosphor Compounds (POHC→CSX)', 19, 7, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(48, 'IX-INT-XX-054', 'Plastic Pellets (POHC→CSX)', 21, 8, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(49, 'IX-INT-XX-055', 'Plastic Pellets (CSX→POHC)', 21, 8, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(50, 'IX-INT-XX-056', 'Forged Components (POHC→CSX)', 10, 2, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(51, 'IX-INT-XX-057', 'Forged Components (CSX→POHC)', 10, 2, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(52, 'IX-INT-XX-058', 'Stainless Bar (POHC→CSX)', 26, 2, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(53, 'IX-INT-XX-059', 'Stainless Bar (CSX→POHC)', 26, 2, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(54, 'IX-INT-XX-060', 'Stainless Slab (CSX→POHC)', 27, 2, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(55, 'IX-INT-XX-061', 'Stainless Slab (POHC→CSX)', 27, 2, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(56, 'IX-INT-XX-062', 'Steel Billets (CSX→POHC)', 29, 2, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(57, 'IX-INT-XX-063', 'Steel Billets (CSX→POHC)', 29, 2, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(58, 'IX-INT-XX-064', 'Steel Plate (CSX→POHC)', 31, 2, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(59, 'IX-INT-XX-065', 'Scrap Steel (POHC→CSX)', 25, 6, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(60, 'IX-INT-XX-066', 'Coal (CSX→POHC)', 6, 3, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(61, 'IX-INT-XX-067', 'Frozen Foods (POHC→CSX)', 11, 10, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(62, 'IX-INT-XX-068', 'Packaged Meats (CSX→POHC)', 18, 10, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(63, 'IX-INT-XX-069', 'Argon (POHC→CSX)', 3, 9, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(64, 'IX-INT-XX-070', 'Industrial Gases (CSX→POHC)', 14, 9, 6, 5, 0, 0, 1, 0, 1, 'CSX→POHC', ''),
(65, 'IX-INT-XX-071', 'LPG (POHC→CSX)', 15, 9, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', ''),
(66, 'IX-INT-XX-072', 'Methyl Methacrylate (POHC→CSX)', 17, 9, 5, 6, 0, 0, 1, 0, 1, 'POHC→CSX', '');

INSERT INTO `cars` (`Id`, `reporting_marks`, `car_code_id`, `current_location_id`, `position`, `status`, `handled_by_job_id`, `remarks`, `load_count`, `home_location`, `RFID_code`) VALUES
(2, 'BO8300', 1, 5, NULL, 'EMPTY', NULL, 'Coil 55ft', 0, 5, NULL),
(3, 'BO8405', 2, 6, NULL, 'EMPTY', NULL, 'Flatcar 53ft', 0, 6, NULL),
(4, 'BO8417', 2, 6, NULL, 'EMPTY', NULL, 'Flatcar 53ft', 0, 6, NULL),
(5, 'BO8451', 2, 5, NULL, 'EMPTY', NULL, 'Flatcar 53ft', 0, 5, NULL),
(6, 'BO8476', 2, 6, NULL, 'EMPTY', NULL, 'Flatcar 53ft', 0, 6, NULL),
(9, 'BO10389', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(10, 'BO11027', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(11, 'BO11137', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(12, 'BO30222', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 6, NULL),
(13, 'BO30963', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 6, NULL),
(14, 'BO31000', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 6, NULL),
(15, 'BO73133', 3, 3, NULL, 'EMPTY', NULL, 'Hopper 45ft', 0, 3, NULL),
(16, 'BO132315', 4, 3, NULL, 'EMPTY', NULL, 'Hopper 50ft', 0, 3, NULL),
(17, 'BO132392', 4, 3, NULL, 'EMPTY', NULL, 'Hopper 50ft', 0, 3, NULL),
(18, 'BO133007', 4, 3, NULL, 'EMPTY', NULL, 'Hopper 50ft', 0, 3, NULL),
(19, 'BO283057', 5, 6, NULL, 'EMPTY', NULL, 'Boxcar 50ft', 0, 6, NULL),
(20, 'BO283069', 5, 6, NULL, 'EMPTY', NULL, 'Boxcar 50ft', 0, 6, NULL),
(21, 'BO371604', 6, 5, NULL, 'EMPTY', NULL, 'Gondola 50ft', 0, 5, NULL),
(23, 'BO467071', 5, 5, NULL, 'EMPTY', NULL, 'Boxcar 40ft', 0, 5, NULL),
(24, 'BO467439', 5, 6, NULL, 'EMPTY', NULL, 'Boxcar 40ft', 0, 6, NULL),
(25, 'BO551470', 6, 5, NULL, 'EMPTY', NULL, 'Gondola 50ft', 0, 5, NULL),
(26, 'BO600401', 7, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(27, 'BO600409', 7, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(28, 'BO600421', 7, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(29, 'BO625082', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(30, 'BO625238', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(31, 'BO625509', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(32, 'BO625943', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(33, 'BO628038', 7, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(34, 'BO631140', 7, 5, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 5, NULL),
(35, 'CBQ171856', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(36, 'CO2052', 8, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(37, 'CO2063', 8, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(39, 'CO142374', 3, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(41, 'CR477935', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(42, 'EL8063', 2, 5, NULL, 'EMPTY', NULL, 'Flatcar 52ft', 0, 5, NULL),
(43, 'EL66410', 5, 5, NULL, 'EMPTY', NULL, 'Boxcar 50ft', 0, 5, NULL),
(46, 'KSMX101', 7, 6, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 6, NULL),
(47, 'KSMX105', 7, 5, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 5, NULL),
(48, 'KSMX110', 7, 6, NULL, 'EMPTY', NULL, 'Hopper 34ft', 0, 6, NULL),
(50, 'MOW0017', 9, 5, NULL, 'EMPTY', NULL, 'Tank 40ft', 0, 5, NULL),
(51, 'MSTL52763', 5, 6, NULL, 'EMPTY', NULL, 'Boxcar 40ft', 0, 6, NULL),
(52, 'NW12986', 7, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(53, 'NW12988', 3, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(54, 'NW32800', 2, 6, NULL, 'EMPTY', NULL, 'Flatcar 52ft', 0, 6, NULL),
(55, 'NYC47516', 5, 5, NULL, 'EMPTY', NULL, 'Boxcar 50ft', 0, 5, NULL),
(58, 'PRR498647', 9, 6, NULL, 'EMPTY', NULL, 'Tank 40ft', 0, 6, NULL),
(59, 'PRR702186', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(61, 'PRR728012', 3, 5, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 5, NULL),
(62, 'RDG99143', 1, 6, NULL, 'EMPTY', NULL, 'Coil 55ft', 0, 6, NULL),
(63, 'RDG107333', 5, 6, NULL, 'EMPTY', NULL, 'Boxcar 50ft', 0, 6, NULL),
(64, 'REX350', 10, 5, NULL, 'EMPTY', NULL, 'Reefer 50ft', 0, 5, NULL),
(65, 'RMLI2018', 5, 5, NULL, 'EMPTY', NULL, 'Boxcar 40ft', 0, 5, NULL),
(66, 'RMP50', 5, 6, NULL, 'EMPTY', NULL, 'Boxcar 40ft', 0, 6, NULL),
(68, 'URR15003', 3, 3, NULL, 'EMPTY', NULL, 'Hopper 50ft', 0, 3, NULL),
(69, 'URR15022', 3, 3, NULL, 'EMPTY', NULL, 'Hopper 50ft', 0, 3, NULL),
(70, 'URR15044', 3, 3, NULL, 'EMPTY', NULL, 'Hopper 50ft', 0, 3, NULL),
(71, 'URTX63627', 10, 6, NULL, 'EMPTY', NULL, 'Reefer 40ft', 0, 6, NULL),
(74, 'UTLX36299', 9, 5, NULL, 'EMPTY', NULL, 'Tank 40ft', 0, 5, NULL),
(76, 'WLE621', 3, 6, NULL, 'EMPTY', NULL, 'Hopper 40ft', 0, 6, NULL),
(78, 'COST1', 11, 4, NULL, 'EMPTY', NULL, 'Scale test car', 0, 6, NULL),
(79, 'COW86', 11, 4, NULL, 'EMPTY', NULL, 'MOW camp car', 0, 6, NULL),
(80, 'CO377700', 12, 4, NULL, 'EMPTY', NULL, 'MOW crane car', 0, 6, NULL);

INSERT INTO `jobs` (`Id`, `name`, `description`) VALUES
(1, 'D749', 'CSX Neville Island Switcher.\n- Demmler Yard: Pick up for Scully Yard\n- Demmler Yard: Pick up for Neville Island\n- South Yard: Set out inbound; Pick up for Demmler Yard\n- Demmler Yard: Set out outbound'),
(2, 'NVL', 'POHC Neville Local.\n- Scully Yard: Pick up for Neville Island and Demmler Yard\n- South Yard: Set out; Pick up Neville Island block\n- Neville Island: Spot and pull for island, Scully, and Demmler\n- South Yard: Set out; Pick up for Scully Yard\n- Scully Yard: Set out outbound'),
(3, 'SY1', 'South Yard yardmaster (SY1) — inter-island switching on Neville Island.\nRetrieve and stage cars across North, East, and West yards for island industries.\nSort inbound traffic and build outbound blocks for CSX D749 (via Demmler) and POHC NVL (via Scully).\nD749 and NVL handle industry spotting and interchange; SY1 works the satellite yards only.'),
(4, 'CK-1', 'Coke transfer — optional yard move.\nMove coke loads from East Yard to South Yard for weighing and classification when authorized and traffic warrants.\nRun only when it will not interfere with NVL or passenger movements.'),
(5, 'CKX', 'Coke extra — optional outbound coke move.\nDepart South Yard with weighed coke loads when enough cars are ready.\nMay run via CSX (Demmler) or POHC as directed by car routing.');

CREATE TABLE `D749` (
  `step_number` int(11) NOT NULL,
  `station` int(11) DEFAULT NULL,
  `pickup` char(1) DEFAULT NULL,
  `setout` char(1) DEFAULT NULL,
  `remarks` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`step_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `D749` (`step_number`, `station`, `pickup`, `setout`, `remarks`) VALUES
(10, 10, 'T', 'F', 'Pick up inbound for Scully Yard'),
(20, 10, 'T', 'F', 'Pick up inbound for Neville Island'),
(30, 8, 'T', 'T', 'Set out inbound; Pick up outbound for Demmler Yard'),
(40, 10, 'F', 'T', 'Set out outbound at Demmler Yard');

CREATE TABLE `NVL` (
  `step_number` int(11) NOT NULL,
  `station` int(11) DEFAULT NULL,
  `pickup` char(1) DEFAULT NULL,
  `setout` char(1) DEFAULT NULL,
  `remarks` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`step_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `NVL` (`step_number`, `station`, `pickup`, `setout`, `remarks`) VALUES
(10, 9, 'T', 'F', 'Pick up inbound for Neville Island'),
(20, 9, 'T', 'F', 'Pick up inbound for Demmler Yard'),
(30, 8, 'T', 'T', 'Set out; Pick up Neville Island block'),
(40, 3, 'T', 'T', 'Island work — pick up for Neville Island, Scully Yard, and Demmler Yard'),
(50, 8, 'T', 'T', 'Set out; Pick up outbound for Scully Yard'),
(60, 9, 'F', 'T', 'Set out outbound at Scully Yard');

CREATE TABLE `SY1` (
  `step_number` int(11) NOT NULL,
  `station` int(11) DEFAULT NULL,
  `pickup` char(1) DEFAULT NULL,
  `setout` char(1) DEFAULT NULL,
  `remarks` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`step_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `SY1` (`step_number`, `station`, `pickup`, `setout`, `remarks`) VALUES
(10, 8, 'T', 'F', 'Pick up inbound cars from D749 and NVL for classification'),
(20, 11, 'T', 'T', 'Retrieve and stage cars at North Yard'),
(30, 12, 'T', 'T', 'Retrieve and stage cars at East Yard'),
(40, 2, 'T', 'T', 'Retrieve and stage cars at West Yard'),
(50, 8, 'F', 'T', 'Build NVL industry block; stage CSX block for D749 (Demmler) and POHC block for NVL (Scully)');

CREATE TABLE `CK-1` (
  `step_number` int(11) NOT NULL,
  `station` int(11) DEFAULT NULL,
  `pickup` char(1) DEFAULT NULL,
  `setout` char(1) DEFAULT NULL,
  `remarks` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`step_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `CK-1` (`step_number`, `station`, `pickup`, `setout`, `remarks`) VALUES
(10, 12, 'T', 'F', 'Pick up coke loads at East Yard'),
(20, 8, 'F', 'T', 'Set out coke loads at South Yard for weighing/classification');

CREATE TABLE `CKX` (
  `step_number` int(11) NOT NULL,
  `station` int(11) DEFAULT NULL,
  `pickup` char(1) DEFAULT NULL,
  `setout` char(1) DEFAULT NULL,
  `remarks` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`step_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `CKX` (`step_number`, `station`, `pickup`, `setout`, `remarks`) VALUES
(10, 8, 'T', 'F', 'Pick up weighed coke loads at South Yard'),
(20, 10, 'F', 'T', 'Set out coke for CSX at Demmler Yard');

INSERT INTO `pu_criteria` (`id`, `job_id`, `step_nbr`, `car_status`, `commodity_id`, `car_code_id`, `dest_station_id`) VALUES
(NULL, 'D749', 10, '', NULL, NULL, 9),
(NULL, 'D749', 20, '', NULL, NULL, 3),
(NULL, 'D749', 30, '', NULL, NULL, 10),
(NULL, 'NVL', 10, '', NULL, NULL, 3),
(NULL, 'NVL', 20, '', NULL, NULL, 10),
(NULL, 'NVL', 30, '', NULL, NULL, 3),
(NULL, 'NVL', 40, '', NULL, NULL, 3),
(NULL, 'NVL', 40, '', NULL, NULL, 9),
(NULL, 'NVL', 40, '', NULL, NULL, 10),
(NULL, 'NVL', 50, '', NULL, NULL, 9),
(NULL, 'SY1', 10, '', NULL, NULL, 3),
(NULL, 'SY1', 10, '', NULL, NULL, 10),
(NULL, 'SY1', 10, '', NULL, NULL, 9),
(NULL, 'SY1', 20, '', NULL, NULL, 3),
(NULL, 'SY1', 20, '', NULL, NULL, 8),
(NULL, 'SY1', 30, '', NULL, NULL, 3),
(NULL, 'SY1', 30, '', NULL, NULL, 8),
(NULL, 'SY1', 40, '', NULL, NULL, 3),
(NULL, 'SY1', 40, '', NULL, NULL, 8),
(NULL, 'CK-1', 10, 'Loaded', NULL, NULL, 8),
(NULL, 'CKX', 10, 'Loaded', NULL, NULL, 10);

-- Reset AUTO_INCREMENT counters
ALTER TABLE `cars` AUTO_INCREMENT = 81;
ALTER TABLE `commodities` AUTO_INCREMENT = 34;
ALTER TABLE `car_codes` AUTO_INCREMENT = 13;
ALTER TABLE `locations` AUTO_INCREMENT = 18;
ALTER TABLE `routing` AUTO_INCREMENT = 8;
ALTER TABLE `shipments` AUTO_INCREMENT = 67;
ALTER TABLE `jobs` AUTO_INCREMENT = 6;

-- Summary
-- routing: 7
-- locations: 17
-- commodities: 33
-- car_codes: 12
-- shipments: 66
-- cars: 63
-- jobs: 5
-- pu_criteria: 21
-- empty_locations: 0
